### ISSUE TITLE
Match off of first 100 versions rather than last 100

### ISSUE THREAD

**Issue by JackHowa** [SmartsquareGmbH/delete-old-packages#15]
We're trying to clean up the latest versions. (Trying to retroactively clean up packages may be more difficult in our case.) Is there any reason why allowing for the first 100 versions would be problematic. https://github.com/SmartsquareGmbH/delete-old-packages/blob/master/src/strategy/user-strategy.js#L10

I'm getting an issue `If you have more than 100 versions and none of the 100 oldest versions match, no packages will be deleted!`

**Comment by rubengees** [comment]
Do you have more than 100 versions that you do not want to delete? Why would you want to sort from the other side?

**Comment by JackHowa** [comment]
Really appreciate your work on this Action. I like the props table in the documentation. 

> Do you have more than 100 versions that you do not want to delete?

Yes ... sort of. I can reliably match version names to delete and reduce the amount of versions starting from the beginning (we changed our naming standards). Does that kind of make sense?

**Comment by JackHowa** [comment]
@rubengees is this something that you think others might want? an odd edgecase? it's been working as expected in my tests. if not, I can close the pr?

**Comment by rubengees** [comment]
Sorry for the late answer! I'm always a bit careful when adding more options to avoid feature creep and complexity. What is the use case for keeping more than 100 versions? Is it possible to instead have a regex that matches only the versions you actually want to delete?

Let's keep the PR (thanks for that!) open until I come to a conclusion.

**Comment by JackHowa** [comment]
ok. I will keep it open. Right now, I'm unsure if I can delete some of the older versions. But some of the newer ones have a more precise naming scheme that makes me confident that I can delete them. 

Imagine there's a limit of 4 not 100 (list goes new to old): 

124 - want to keep
123beta.5 - want to keep latest version with "beta" in it
123beta.4 - can delete
123beta.3 - can delete
123beta.2 - can delete
123beta.1 - can delete
123 - not sure if I can delete
122 - not sure if I can delete
121 - not sure if I can delete
120 - not sure if I can delete

I would match for "delete" starting from the newest version.

**Comment by JackHowa** [comment]
closing as it's now been done
