### ISSUE TITLE
Allow to keep N number of versions

### ISSUE THREAD

**Issue by chrisjohnson00** [SmartsquareGmbH/delete-old-packages#2]
I'd like to be able to specify keeping N number of versions, where N > 20.  Currently this action limits `keep` to 20 or less.

**Comment by rubengees** [comment]
This maximum Github allows is 100, would that work?

We need to watch out for the rate limit though, with Github's v4 API that is easy to hit.

**Comment by rubengees** [comment]
I have release version `0.1.1` with a new limit of 100 which is the most Github allows.

**Comment by chrisjohnson00** [comment]
Perfect, thanks.  I was hoping for around 30 or so, so this will work nicely.
