### ISSUE TITLE
Error message when more than 20 messages

### ISSUE THREAD

**Issue by skin27** [SmartsquareGmbH/delete-old-packages#32]
I have just taken over managing a GitHub Workflow from a colleague. One of the first thing I did was to add a job to delete, a few more packages (so now there are 39 packages). Then I run into an error and found out that the action works at most with 20 packages. From your readme:

"The action works by getting at most 20 packages with at most the oldest 100 versions of each, applying the filters (see table below) on them and then deleting the matching versions."

My questions:

1. Why is this limit there? Isn't 20 a bit low?
2. Isn't it better to check if the limit is exceeded before the action is run and then report a readable error? Something like: "Maximum number of package names is exceeded. 39 package names are listed, but a maximum of 20 is allowed".

In the attached log file the error I now see.
[delete_old_packages_error.log](https://github.com/SmartsquareGmbH/delete-old-packages/files/12557206/delete_old_packages_error.log)

**Comment by rubengees** [comment]
Hi, thanks for using this action,

1. I think this is a limit we had for historical reasons and is not actually needed anymore.
2. The error you posted seems to be the code of this action? is this really what is printed?

In any case, I will check this later and remove the check!

**Comment by skin27** [comment]
Yeah, the whole code was what printed. When I could use more than 20 than would be fine too. Keep up the good work.
