### ISSUE TITLE
Error: HttpError: You cannot delete the last version of a package. You must delete the package instead.

### ISSUE THREAD

**Issue by skin27** [SmartsquareGmbH/delete-old-packages#33]
If I add a new package and there is only one version yet I get the following error for the GitHub API:

"Error: HttpError: You cannot delete the last version of a package. You must delete the package instead."

In this case it's OK for me to delete the whole package

**Comment by rubengees** [comment]
This is something this action does not support yet. I guess it would be possible, but needs explicit handling. I'm marking this as a feature request.

**Comment by tisoft** [comment]
I ran into the same issue and have created a PR to fix it.

**Comment by rubengees** [comment]
@tisoft Thanks! I'll try to review the PR (and the others you've created) this week :slightly_smiling_face:
