### ISSUE TITLE
Question: Support for GitHub Container Registry?

### ISSUE THREAD

**Issue by andygrunwald** [SmartsquareGmbH/delete-old-packages#5]
I found this project via https://github.com/actions/delete-package-versions/issues/5#issuecomment-728883481.
Thanks a lot for your efforts.

### Question

Do you know if this action works also with the (new) [GitHub Container Registry](https://docs.github.com/en/free-pro-team@latest/packages/getting-started-with-github-container-registry/about-github-container-registry)?

When you are using [GitHub Packages](https://docs.github.com/en/free-pro-team@latest/packages/publishing-and-managing-packages/about-github-packages) with Docker, it is recommended to use the GitHub Container Registry.
One difference is: The GitHub Container Registry is not bound to a repository. More to an organization.
A relation can be set up to the repository (e.g., via Docker labels).

### Usecase

I use GitHub Actions to build new Docker images + push them to the Container Registry on each master push (they also get deployed directly). My goal is to keep the last X versions of an image in the registry.

**Comment by rubengees** [comment]
It works with the repository bound GH container registry, probably not for the organization wide registry. Once I have time, I'll investigate if that can be added :+1:

**Comment by rubengees** [comment]
Note for myself: It seems these can be fetched via the `packages` field in the [User object](https://docs.github.com/en/free-pro-team@latest/graphql/reference/objects#user). We would need a way to distinguish the repository bound query from the user bound query.

**Comment by ewerkema** [comment]
Found this article regarding api support: https://github.community/t/github-container-registry-ghcr-io-packages-not-appearing-in-api/130133. Seems they are still working to provide delete functionality for ghcr packages. Thanks for building this package!

**Comment by rubengees** [comment]
I've implemented deletion by user and organization. Once the GraqhQL api also returns the container packages, this can be finished.

**Comment by Niek** [comment]
Thanks for your work @rubengees - hopefully we can delete old container versions soon.

**Comment by amiantos** [comment]
Any chance on support for container registry now? I see that the GraphQL API returns container registry now.

**Comment by rubengees** [comment]
@amiantos Do you have docs or an example query for that? I just tried a GraphQL query for our organization and it did not return container packages.

**Comment by amiantos** [comment]
Maybe I am getting things mixed up. But it might depend on if you are using a GITHUB_TOKEN vs a PAT.

https://github.community/t/github-token-has-no-access-to-new-container-rest-apis/170395
https://github.community/t/github-container-registry-ghcr-io-packages-not-appearing-in-api/130133/17

This user has supposedly figured out how to access GHCR using the deprecated official action:
https://github.com/actions/delete-package-versions/issues/28#issuecomment-804394142
https://github.com/actions/delete-package-versions/compare/main...kc1r74p:main

Sorry I can't offer more specific help, all this stuff is greek to me but I am starting to feel the itch to dive in myself just because I'd like to migrate over to container registry if we can do so. Just seems like automating deletion is the missing link.

**Comment by rubencherbit** [comment]
Actually, I think there is only Rest API and github don't communicate on a release for graphql
https://docs.github.com/en/rest/reference/packages
https://github.blog/changelog/2021-02-17-packages-delete-and-restore-for-all-packages/

**Comment by rubengees** [comment]
@adrianinsaval GitHub has not released supported in the GraphQL API yet. I don't think it will happen anytime soon so our best bet will be to use the [Rest API](https://docs.github.com/en/rest/packages#about-the-github-packages-api). I just tried it a bit and it seems to have the operations we need to work with it.

I think the best approach would be to introduce a new optional `packageType` parameter which can be one of the types supported by the graphql API (e.g. `NPM`) or `container` which would then trigger the Rest API path.

**Comment by amiantos** [comment]
To help others, I use this action now in some repos and it does the job of cleaning out old containers from container registry: https://github.com/snok/container-retention-policy

**Comment by lrstanley** [comment]
Can confirm https://github.com/snok/container-retention-policy works great. I have a [reusable task](https://github.com/lrstanley/.github/blob/master/.github/workflows/docker-prune.yml) that I include from many of my other repositories, that prunes at different rates depending on if it's an alpha/beta/rc package, as well as a packaged from a PR build.

**Comment by rubengees** [comment]
This is now supported as of [v0.5.0](https://github.com/SmartsquareGmbH/delete-old-packages/releases/tag/v0.5.0) (sorry for the long delay)! It comes with some constraints though, so check the new section in the [README](https://github.com/SmartsquareGmbH/delete-old-packages/releases/tag/v0.5.0).

**Comment by relthyg** [comment]
There is no new section in the README anymore; it has bee removed [here](https://github.com/SmartsquareGmbH/delete-old-packages/commit/c3d9a8b0f91e555a678d850df8fd8f8dd5f7751a#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L90-L100).
