### ISSUE TITLE
Feature Request: Dry Run

### ISSUE THREAD

**Issue by peter-dolkens** [SmartsquareGmbH/delete-old-packages#7]
Would be great if there was a "dry run" mode for this which just printed out which packages would be caught by the filters.

**Comment by rubengees** [comment]
That makes sense, will add :+1:

**Comment by rubengees** [comment]
Implemented in [0.3.0](https://github.com/SmartsquareGmbH/delete-old-packages/releases/tag/v0.3.0)!
