### ISSUE TITLE
Feature Request: Support NuGet version filters

### ISSUE THREAD

**Issue by peter-dolkens** [SmartsquareGmbH/delete-old-packages#8]
In addition to regex, it would be amazing if this action supported `nuget-pattern` or similar, which let us use the version-range syntax used by NuGet.

Notation | Applied rule | Description
-- | -- | --
1.0 | x ≥ 1.0 | Minimum version, inclusive
(1.0,) | x > 1.0 | Minimum version, exclusive
[1.0] | x == 1.0 | Exact version match
(,1.0] | x ≤ 1.0 | Maximum version, inclusive
(,1.0) | x < 1.0 | Maximum version, exclusive
[1.0,2.0] | 1.0 ≤ x ≤ 2.0 | Exact range, inclusive
(1.0,2.0) | 1.0 < x < 2.0 | Exact range, exclusive
[1.0,2.0) | 1.0 ≤ x < 2.0 | Mixed inclusive minimum and exclusive maximum version
(1.0) | invalid | invalid

Source: https://docs.microsoft.com/en-us/nuget/concepts/package-versioning#version-ranges

**Comment by rubengees** [comment]
Good idea! Instead of nuget I would go with semver though because:

- It is more widely adopted.
- There is a popular npm package.

I will try to add a new input `semver-version` which can be set _instead of_ `version-pattern`.

**Comment by rubengees** [comment]
Implemented in [0.3.0](https://github.com/SmartsquareGmbH/delete-old-packages/releases/tag/v0.3.0)!

**Comment by peter-dolkens** [comment]
> Good idea! Instead of nuget I would go with semver though because:
> 
> * It is more widely adopted.
> * There is a popular npm package.

Yup, I was originally going to say semver, but thought I'd recommend the package-native syntax.

Of course I completely overlooked that github supports more than just nuget packages 🤦🏻 

Will try this out, thanks!
